### ISSUE TITLE
External DB credentials are not passed to containers

### ISSUE THREAD

**Issue by jbeakley** [blackducksoftware/synopsys-operator#626] opened 2019-07-04 14:38 UTC
I am trying to create a BlackDuck instance with an external RDS database: 
{code:java}
synopsysctl.exe create blackduck blackduck --namespace bd --size small --expose-service NODEPORT --external-postgres-host <host> --external-postgres-port 5432 --external-postgres-admin blackduck --external-postgres-user blackduck_user --external-postgres-admin-password <password>--external-postgres-user-password <password>
{code}

The following command stores the password correctly but the containers still report wrong password error. 

In version 2019.4.0 i was able to do: 
{code:java}
synopsysctl.exe create blackduck blackduck --size small --expose-service NODEPORT --external-postgres-host <host> --external-postgres-port 5432 --external-postgres-admin blackduck --external-postgres-user blackduck_user --external-postgres-admin-password <password>--external-postgres-user-password <password>
{code}

**Comment by msenmurugan** [comment] 2019-07-09 17:06
duplicate of #630

**Closed by msenmurugan** 2019-07-09 17:06 UTC
Labels: synopsysctl
