### ISSUE TITLE
synopsysctl cannot be configured to deploy an instance without persistent storage

### ISSUE THREAD

**Issue by jdartigalongue** [blackducksoftware/synopsys-operator#160] opened 2019-04-16 11:51 UTC
**Describe the bug**
Using persistent storage is the default option and the --persistent-storage flag doesn't take a true/false parameter and therefore, there is no way to deploy an instance without persistent storage

**Environment (please complete the following information):**
 - Openshift Version:  OCP 3.1

**To Reproduce**
`./synopsysctl create blackduck nopv --persistent-storage false`

**Expected behavior**
The instance is created with persistent storage set to false

**Actual behavior**
Error: This command only accepts 1 argument

**Comment by mphammer** [comment] 2019-04-24 19:24
The problem is that `--persistent-storage` is a flag that does not take in a value. Including the flag means it is true and ignoring the flag means it is false. Thus, when a value is provided it thinks it is another argument to the command and you get the error `ERRO[0000] this command takes 1 argument`.

Notice how most flags are `--flag-name <type>` but this is just `--flag-name`

```
      ...
      --external-postgres-admin string            Name of Admin for Postgres
      --external-postgres-admin-password string   Password for the Postgres Admin
      --external-postgres-host string             Host for Postgres
      --external-postgres-port int                Port for Postgres
      --external-postgres-ssl                     Use SSL for Postgres connection
      --external-postgres-user string             Username for Postgres
      --external-postgres-user-password string    Password for a Postgres User
  -h, --help                                      help for blackduck
      --image-registries strings                  List of image registries
      --image-uid-map-file-path string            Absolute path to a file containing a map of Container UIDs to Tags
      --license-key string                        License Key of Black Duck
      --liveness-probes                           Enable liveness probes
      --mock string                               Prints the resource spec instead of creating it [json/yaml]
      --persistent-storage                        Enable persistent storage
      ...
```

**Comment by yashbhutwala** [comment] 2019-06-11 20:52
This flag has changed now to be a string, and does what @jdartigalongue originally wanted.  Closing.

**Closed by yashbhutwala** 2019-06-11 20:52 UTC
