### ISSUE TITLE
"The Black Duck server did not respond in time." when using NodePort

### ISSUE THREAD

**Issue by SS-TT** [blackducksoftware/synopsys-operator#1197] opened 2020-01-24 10:06 UTC
**What happened**:
Our BD instance has been installed and exposed using `NodePort`.
This means that we can reach it using a link such as `https://our.server.local:30056`.
When loading a project, however, we had the following error:

> The Black Duck server did not respond in time.

A quick inspection of network requests showed that a lot of `xhr` requests are failing, because they're sent to `https://our.server.local` (without the correct port).

This is one sample url:
> https://our.server.local/api/projects/25f0acce-c46e-4cce-85c4-f0b39a0530a1/versions

while the correct one should be 
> https://our.server.local:30056/api/projects/25f0acce-c46e-4cce-85c4-f0b39a0530a1/versions

Our guess is that internal links are generated using hostname only, while they should use the port too.

**What you expected to happen**:

Project page should load without errors.

**How to reproduce it (as minimally and precisely as possible)**:

Install BD and expose it as NodePort.
Create a project and navigate to that project.

**Screenshots/additional context**:

**Environment (please complete the following information):**
- Kubernetes version (use `kubectl version`): 1.17
- Openshift version (use `oc version`):
- Cloud provider or hardware configuration: on-prem
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Others:

**Comment by msenmurugan** [comment] 2020-01-24 13:14
@SS-TT In order to Black Duck respomd to node port, please set the environment variable PUBLIC_HUB_WEBSERVER_PORT as node port value.

**Comment by SS-TT** [comment] 2020-01-24 16:41
Can this be added after the first installation or do we need to reinstall everything from scratch?

**Comment by yashbhutwala** [comment] 2020-01-24 17:45
@SS-TT you would do it after the installation, in fact, part of the issue is that it has to be done after the installation because `NodePort` would be different every time.

You can run something like: `synopsysctl update blackduck <NAME> --environs="PUBLIC_HUB_WEBSERVER_PORT:<YOUR NODEPORT>"`

**Comment by msenmurugan** [comment] 2020-01-24 17:53
@SS-TT Could you please let us know once it is worked, so that we can close this issue?

**Comment by SS-TT** [comment] 2020-01-27 08:53
Actually launching that command, with correct hub name and port, caused all the pods to go into an error state, eventually failing with CrashLoopBackOff status.

Pasting logs from all the pods may be too much, so I'm waiting for more instructions.

**Comment by yashbhutwala** [comment] 2020-01-27 13:04
@SS-TT at least the redacted operator logs would be helpful.  Otherwise, we can have you contact through support for a thorough troubleshooting:
[community.synopsys.com/s](community.synopsys.com/s)

**Comment by SS-TT** [comment] 2020-01-27 15:36
We ended up reinstalling, this is the commands that we launched:

`./synopsysctl create blackduck bd2020 --namespace bd --license-key myLicense --expose-ui NODEPORT --admin-password password --postgres-password password --user-password password`

> INFO[0000] creating Black Duck 'bd2020' in namespace 'bd'...
> INFO[0000] successfully submitted Black Duck 'bd2020' into namespace 'bd'

(port was taken from our NodePort and its correct)
`./synopsysctl update blackduck bd2020 --environs=PUBLIC_HUB_WEBSERVER_HOST:our.host.local,PUBLIC_HUB_WEBSERVER_PORT:32355 -n bd -v trace`

> DEBU[0000] flag 'admin-password': UNCHANGED
> DEBU[0000] flag 'auth-custom-ca-file-path': UNCHANGED
> DEBU[0000] flag 'certificate-file-path': UNCHANGED
> DEBU[0000] flag 'certificate-key-file-path': UNCHANGED
> DEBU[0000] flag 'certificate-name': UNCHANGED
> DEBU[0000] flag 'db-prototype': UNCHANGED
> DEBU[0000] flag 'desired-state': UNCHANGED
> DEBU[0000] flag 'enable-binary-analysis': UNCHANGED
> DEBU[0000] flag 'enable-source-code-upload': UNCHANGED
> DEBU[0000] flag 'environs': CHANGED
> DEBU[0000] flag 'environs': NOT FOUND
> DEBU[0000] flag 'expose-ui': UNCHANGED
> DEBU[0000] flag 'external-postgres-admin': UNCHANGED
> DEBU[0000] flag 'external-postgres-admin-password': UNCHANGED
> DEBU[0000] flag 'external-postgres-host': UNCHANGED
> DEBU[0000] flag 'external-postgres-port': UNCHANGED
> DEBU[0000] flag 'external-postgres-ssl': UNCHANGED
> DEBU[0000] flag 'external-postgres-user': UNCHANGED
> DEBU[0000] flag 'external-postgres-user-password': UNCHANGED
> DEBU[0000] flag 'help': UNCHANGED
> DEBU[0000] flag 'image-registries': UNCHANGED
> DEBU[0000] flag 'insecure-skip-tls-verify': UNCHANGED
> DEBU[0000] flag 'kubeconfig': UNCHANGED
> DEBU[0000] flag 'license-key': UNCHANGED
> DEBU[0000] flag 'liveness-probes': UNCHANGED
> DEBU[0000] flag 'migration-mode': UNCHANGED
> DEBU[0000] flag 'mock': UNCHANGED
> DEBU[0000] flag 'namespace': CHANGED
> DEBU[0000] flag 'namespace': NOT FOUND
> DEBU[0000] flag 'node-affinity-file-path': UNCHANGED
> DEBU[0000] flag 'postgres-claim-size': UNCHANGED
> DEBU[0000] flag 'postgres-password': UNCHANGED
> DEBU[0000] flag 'proxy-certificate-file-path': UNCHANGED
> DEBU[0000] flag 'pull-secret-name': UNCHANGED
> DEBU[0000] flag 'registry': UNCHANGED
> DEBU[0000] flag 'size': UNCHANGED
> DEBU[0000] flag 'type': UNCHANGED
> DEBU[0000] flag 'user-password': UNCHANGED
> DEBU[0000] flag 'verbose-level': CHANGED
> DEBU[0000] flag 'verbose-level': NOT FOUND
> DEBU[0000] flag 'version': UNCHANGED
> INFO[0000] updating Black Duck 'bd2020' in namespace 'bd'...
> INFO[0000] successfully submitted updates to Black Duck 'bd2020' in namespace 'bd'

This is operator's log from the moment we launched the previous command:

> time="2020-01-27T15:25:28Z" level=debug msg="attempting to open db host bd2020-blackduck-postgres.bd.svc.cluster.local for database postgres"
> time="2020-01-27T15:25:28Z" level=debug msg="connected to db host bd2020-blackduck-postgres.bd.svc.cluster.local for database postgres"
> time="2020-01-27T15:25:28Z" level=info msg="updating the config map bd2020-blackduck-config in bd namespace"
> time="2020-01-27T15:25:28Z" level=info msg="updating the deployment bd2020-blackduck-cfssl in bd namespace"
> time="2020-01-27T15:25:38Z" level=info msg="updating the deployment bd2020-blackduck-webserver in bd namespace"
> time="2020-01-27T15:25:39Z" level=info msg="updating the deployment bd2020-blackduck-documentation in bd namespace"
> time="2020-01-27T15:25:39Z" level=info msg="updating the deployment bd2020-blackduck-registration in bd namespace"
> time="2020-01-27T15:25:39Z" level=info msg="updating the deployment bd2020-blackduck-zookeeper in bd namespace"
> time="2020-01-27T15:25:39Z" level=info msg="updating the deployment bd2020-blackduck-jobrunner in bd namespace"
> time="2020-01-27T15:25:40Z" level=info msg="updating the deployment bd2020-blackduck-scan in bd namespace"
> time="2020-01-27T15:25:40Z" level=info msg="updating the deployment bd2020-blackduck-authentication in bd namespace"
> time="2020-01-27T15:25:41Z" level=info msg="updating the deployment bd2020-blackduck-webapp-logstash in bd namespace"
> time="2020-01-27T15:25:42Z" level=info msg="updating the deployment bd2020-blackduck-uploadcache in bd namespace"
> time="2020-01-27T15:26:03Z" level=info msg="couldn't register blackduck bd2020: invalid character '<' looking for beginning of value"
> time="2020-01-27T15:26:03Z" level=info msg="Controller.runWorker: processing next item"
> time="2020-01-27T15:26:03Z" level=info msg="Controller.processNextItem: start"
> time="2020-01-27T15:26:45Z" level=debug msg="ObjectUpdated: bd2020"

Finally, this is the description of the operator, where you can see that both host and port are set correctly:

`./synopsysctl describe blackduck`

> Name:         bd2020
> Namespace:
> Labels:       <none>
> Annotations:  synopsys.com/created.by:
> API Version:  synopsys.com/v1
> Kind:         Blackduck
> Metadata:
>   Creation Timestamp:  2020-01-27T13:46:00Z
>   Generation:          4
>   Resource Version:    2635514
>   Self Link:           /apis/synopsys.com/v1/blackducks/bd2020
>   UID:                 1358a3a2-f37b-4e14-9384-a410c43375fa
> Spec:
>   Admin Password:    passwordinbase64
>   Auth Custom Ca:
>   Certificate Name:  default
>   Desired State:
>   Environs:
>     PUBLIC_HUB_WEBSERVER_HOST:our.host.local
>     PUBLIC_HUB_WEBSERVER_PORT:32355
>   Expose Service:      NODEPORT
>   License Key:         license
>   Liveness Probes:     false
>   Namespace:           bd
>   Persistent Storage:  true
>   Postgres Password:   passwordinbase64
>   Seal Key:
>   Size:                Small
>   User Password:       passwordinbase64
>   Version:             2019.10.1
> Status:
>   Ip:     <<NODE_IP_ADDRESS>>:32355
>   State:  Running
> View:
>   Certificate Names:   <nil>
>   Clones:              <nil>
>   Container Tags:      <nil>
>   Environs:            <nil>
>   Node Affinities:
>   Storage Classes:     <nil>
>   Supported Versions:  <nil>
>   Version:
> Events:                <none>

The issue is still not solved, even though the pods are all running now.

**Comment by msenmurugan** [comment] 2020-01-27 18:56
@SS-TT Could you please let us onow whether you are able to login to Black Duck UI?

**Comment by SS-TT** [comment] 2020-01-28 16:22
I can login to Black Duck UI, this happens when navigating to a project.

**Comment by yashbhutwala** [comment] 2020-02-03 17:29
@SS-TT is this still a problem?  If it is, can you please contact support using the link provided above?

If not, it'd be helpful for others, if you provide your redacted solution.

**Closed by yashbhutwala** 2020-02-03 17:29 UTC
