### ISSUE TITLE
synopsysctl deploy fails with: namespace could not be found

### ISSUE THREAD

**Issue by StevenCane** [blackducksoftware/synopsys-operator#984] opened 2019-10-16 08:03 UTC
**What happened**:
Got error from server:
ERRO[0000] synopsyctl failed: please create the namespace 'synopsys-operator' to deploy the 

**What you expected to happen**:
enable blackduck with synopsysctl

**How to reproduce it (as minimally and precisely as possible)**:
./synopsysctl deploy --enable-blackduck
ERRO[0000] synopsyctl failed: please create the namespace 'synopsys-operator' to deploy the Synopsys Operator in namespace scoped 

[root@blackduck install]# kubectl create namespace synopsys-operator
Error from server (AlreadyExists): namespaces "synopsys-operator" already exists

**Environment:**
1.15.5
CentOS Linux release 7.6.1810 (Core)

[root@blackduck install]# kubectl get namespaces
NAME                STATUS   AGE
blackn              Active   10m
default             Active   19m
kube-node-lease     Active   19m
kube-public         Active   19m
kube-system         Active   19m
synopsys-operator   Active   14m

**Comment by msenmurugan** [comment] 2019-10-16 12:00
@StevenCane If you are planning to use Synopsys Operator at `namespaced` scope, then the customer need to create the namespace and maintain the namespace, synopsys operator will use the namespace to install the apps

**Comment by msenmurugan** [comment] 2019-10-16 12:01
@StevenCane If you are satisfied with the answer, please let us know, so that we can close this ticket.

**Comment by StevenCane** [comment] 2019-10-16 21:56
Thanks for your answer.

I try it in several ways with my own namespace:

 >kubectl create namespace sample
namespace/sample created
> ./synopsysctl deploy --enable-blackduck -n sample
ERRO[0000] synopsyctl failed: please create the namespace 'sample' to deploy the Synopsys Operator in namespace scoped

With default namespace:
> ./synopsysctl deploy --enable-blackduck
ERRO[0000] synopsyctl failed: please create the namespace 'synopsys-operator' to deploy the Synopsys Operator in namespace scoped


Sorry at the moment I've no idea where the problem is and I have no idea how I can get more information about my problem (detailed error message)

**Comment by yashbhutwala** [comment] 2019-10-17 11:48
@StevenCane I am not able to reproduce this issue, see the screenshot below.  Can you please specify which version of `synopsysctl`, and `synopsys-operator` are you using?

<img width="809" alt="image" src="https://user-images.githubusercontent.com/5788514/67006187-73411200-f0b2-11e9-89d3-1d71cf47b7c0.png">

**Comment by StevenCane** [comment] 2019-10-17 13:22
very strange on my side it looks like this all the time

![image](https://user-images.githubusercontent.com/31103072/67012530-d900be80-f0f1-11e9-8db9-c17964ee4f63.png)

**Comment by StevenCane** [comment] 2019-10-18 11:12
Hi thanks for your reply,
>kubectl describe crd blackduck
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "blackduck" not found

Now I've installed blackduck  withthout sysnopsysctl on this system. Is it possible to call destroy without destroying my blackduck installation? Therefor is the other namespace blackn

**Comment by yashbhutwala** [comment] 2019-10-18 12:10
This is certainly very peculiar.  

> Now I've installed blackduck withthout sysnopsysctl on this system. Is it possible to call destroy without destroying my blackduck installation? Therefor is the other namespace blackn

In that case, don't run `destroy`.

Can you try running the `deploy` command again with a verbose log level like this: 
`./synopsysctl deploy --enable-blackduck -v debug`? 

Otherwise, we can have you contact through support here for a thorough troubleshooting: 
https://community.synopsys.com/s/

**Comment by yashbhutwala** [comment] 2019-10-30 13:38
@StevenCane were you able to resolve this issue?

**Comment by yashbhutwala** [comment] 2020-01-27 13:05
Closing this since no response since ~2 months.

**Closed by yashbhutwala** 2020-01-27 13:05 UTC
Labels: needs-triage, question
